In [1]:
import pandas as pd
import numpy as np

In [2]:
train_s1 = pd.read_csv("../dataset/train/train_source1.tsv", sep="\t")
train_s2 = pd.read_csv("../dataset/train/train_source2.tsv", sep="\t")
train_s3 = pd.read_csv("../dataset/train/train_source3.tsv", sep="\t")
ground_truth = pd.read_csv("../dataset/train/train_ground_truth.tsv", sep="\t")

test_s1 = pd.read_csv("../dataset/test/test_source1.tsv", sep="\t")
test_s2 = pd.read_csv("../dataset/test/test_source2.tsv", sep="\t")
test_s3 = pd.read_csv("../dataset/test/test_source3.tsv", sep="\t")

In [3]:
print(train_s1.shape)
print(train_s2.shape)
print(train_s3.shape)
print(ground_truth.shape)

(2206821, 4)
(5034616, 4)
(5285603, 4)
(2206821, 2)

In [4]:
train_s1.head()

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

In [5]:
train_s1.info()

<class 'pandas.DataFrame'>
RangeIndex: 2206821 entries, 0 to 2206820
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 67.3 MB

In [6]:
train_s2.info()
train_s3.info()
ground_truth.info()

<class 'pandas.DataFrame'>
RangeIndex: 5034616 entries, 0 to 5034615
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 153.6 MB
<class 'pandas.DataFrame'>
RangeIndex: 5285603 entries, 0 to 5285602
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 161.3 MB
<class 'pandas.DataFrame'>
RangeIndex: 2206821 entries, 0 to 2206820
Data columns (total 2 columns):
 #   Column              Dtype
---  ------              -----
 0   source1_entity_id   str
 1   matched_entity_ids  str
dtypes: str(2)
memory usage: 33.7 MB

In [7]:
train_s1.head()
train_s2.head()
train_s3.head()
ground_truth.head()

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [8]:
print("Source1")
print(train_s1.isnull().sum())

print("\nSource2")
print(train_s2.isnull().sum())

print("\nSource3")
print(train_s3.isnull().sum())

Source1
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

Source2
entity_id                0
business_name            2
business_address    168967
country                  0
dtype: int64

Source3
entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

In [9]:
print(train_s1.duplicated().sum())
print(train_s2.duplicated().sum())
print(train_s3.duplicated().sum())

0
0
0

In [10]:
ground_truth.head(10)

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

In [11]:
sample = ground_truth.iloc[0]
print(sample)

source1_entity_id                                             S1-965667
matched_entity_ids    S2-681193310,S2-743505751,S3-775321672,S3-1129...
Name: 0, dtype: str

In [12]:
train_s1.isnull().sum()

entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

In [13]:
ground_truth.head()

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [ ]:
import re

def clean_text(text):
    if pd.isna(text):
        return ""

    text = text.lower()

    # Replace symbols
    text = text.replace("&", " and ")

    # Remove common legal suffixes
    text = re.sub(r"\b(private|pvt|limited|ltd|corporation|corp|inc|llc|co)\b", " ", text)

    # Remove punctuation
    text = re.sub(r"[^a-z0-9\s]", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text